/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nl.infosys.hartigehap.supplySystem.presentation;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import nl.infosys.hartigehap.supplySystem.businesslogic.IngredientManager;
import nl.infosys.hartigehap.supplySystem.domain.Interface_IngredientReadOnly;

/**
 * Deze klasse bevat de hoofdscherm voor het voorraadbeheer subsysteem.
 *
 * @author Gregor
 */
public class StockOverviewPanel extends javax.swing.JPanel
{

    StockEditDialog voorraadAanpasScherm;
    IngredientManager ingredientManager;
    List<Integer> rodeRijen;
    CustomTableDataModel tableModel;
    CustomStockCellRenderer cellRenderer;

    /**
     * Creates new form VoorraadGUI
     *
     * @param ingredientManager
     */
    public StockOverviewPanel(IngredientManager ingredientManager)
    {
        this.ingredientManager = ingredientManager;
        rodeRijen = new ArrayList<>();
        cellRenderer = new CustomStockCellRenderer(rodeRijen);
        tableModel = new CustomTableDataModel(new String[]
        {
            "Naam", "Voorraad", "Minimale voorraad"
        });

        initComponents();
        vulTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        button_edit = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_stock = new nl.infosys.hartigehap.supplySystem.presentation.CustomJTable();

        setMinimumSize(new java.awt.Dimension(800, 450));
        setPreferredSize(new java.awt.Dimension(800, 450));

        jLabel1.setText("Overzicht voedingsmiddelen");

        button_edit.setText("aanpassen");
        button_edit.setEnabled(false);
        button_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_editActionPerformed(evt);
            }
        });

        table_stock.setModel(tableModel);
        table_stock.setDefaultRenderer(Object.class, cellRenderer);
        table_stock.getColumnModel().getColumn(0).setPreferredWidth(1000);
        table_stock.getColumnModel().getColumn(1).setPreferredWidth(300);
        table_stock.getColumnModel().getColumn(2).setPreferredWidth(300);
        table_stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_stockMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_stock);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(150, 520, Short.MAX_VALUE)
                .addComponent(button_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_edit)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_editActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_button_editActionPerformed
    {//GEN-HEADEREND:event_button_editActionPerformed
        editEvent();
    }//GEN-LAST:event_button_editActionPerformed

    private void table_stockMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_table_stockMouseClicked
    {//GEN-HEADEREND:event_table_stockMouseClicked
        if (evt.getClickCount() > 1 && evt.isConsumed() == false)
        {
            editEvent();
        }
        else
        {
            button_edit.setEnabled(true);
        }

    }//GEN-LAST:event_table_stockMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private nl.infosys.hartigehap.supplySystem.presentation.CustomJTable table_stock;
    // End of variables declaration//GEN-END:variables

    /**
     * Deze klasse verzorgt het vullen van de tabel waar alle producten met hun
     * voorraden in staan.
     *
     * @throws SQLException
     */
    private void vulTabel()
    {
        button_edit.setEnabled(false);

        rodeRijen.clear();
        tableModel.setRowCount(0);

        for (Interface_IngredientReadOnly nutrient : ingredientManager.getIngredients())
        {
            tableModel.addRow(new Object[]
            {
                nutrient.getName(), nutrient.getStock(), nutrient.getMinimumStock()
            });

            if (nutrient.checkUnderMinimumStock())
            {
                rodeRijen.add(tableModel.getRowCount() - 1);
            }
        }
        table_stock.updateRowHeight();
    }

    private void editEvent()
    {
        voorraadAanpasScherm = new StockEditDialog((JFrame) SwingUtilities.getWindowAncestor(this), ingredientManager, ingredientManager.getIngredient(tableModel.getValueAt(table_stock.convertRowIndexToModel(table_stock.getSelectedRow()), 0).toString()));
        vulTabel();
    }

    public void refresh()
    {
        vulTabel();
    }
}
